services:
  db:
    container_name: 'actifai-takehome-db'
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: actifai
    volumes:
      - ./postgres-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d actifai']
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    container_name: 'actifai-takehome-api'
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
